---
- name: Add Custom fact
  hosts: webserver 
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: Create the remote directory
      file:
        path: "{{ remote_dir }}"
        state: directory 
     #   rescurse: yes
    - name: Install the new facts
      copy:
        src: "{{ facts_file }}"
        dest: "{{ remote_dir }}"
    - name: retrieve facts after adding custom fact
      setup: 
        filter: ansible_local
    - name: Output our newly created static
      debug:
        msg: "{{ ansible_local.custom.sample_exam }}" 


