---
# tasks file for sample-mysql
- name: Tasks 9 Create and work with roles
  hosts: web* 
  tasks:
    - name: Create partition
      parted:
        device: /dev/sdb
        number: 1
        state: present 
        part_end: 800MB
    - name: LVM Volume Group
      lvg:
        vg: vg_database
        pvs: /dev/sdb1
        state: present
    - name: LVM Logical Volume     
      lvol:
        lv: lv_mysql
        vg: vg_database
        size: 512m
    - name: XFS filesystem
      filesystem:
        fstype: xfs
        dev: /dev/vg_database/lv_mysql
    - name: Mount LVM
      mount:
        path: /mnt/mysql_backups
        src: /dev/vg_database/lv_mysql
        fstype: xfs
        state: mounted 


        



