---
- name: Welcome Messages
  hosts: all
  gather_facts: no
  tasks:
    - name: Write message proxy
      copy:
        content: "Welcome to HaProxy 2 Server"
        dest: /etc/motd
      when: inventory_hostname in groups ['proxy']
    - name: Write message webservers                
      copy:                                      
        content: "Welcome to Apache2  Server"     
        dest: /etc/motd                          
      when: inventory_hostname in groups['webserver'] 
    - name: Write message database                  
      copy:                                      
        content: "Welcome to MySQL 2 Server"     
        dest: /etc/motd                          
      when: '"database" in group_names' 
   
