---
- name: Create a repository on database severs.
  hosts: proxy 
  tasks:
    - name: Import GPG Public Key
      rpm_key:
        key:  http://repo.mysql.com/RPM-GPG-KEY-mysql
        state: absent
    - name: Add repository on database servers
      yum_repository:
        name: mysql56-community
        file: external_repos
        description: MySQL56  YUM Repo
        baseurl: ftp://labipa.example.com/repo
        gpcheck: 0
        enabled: 1 
        state: present

