---
- name: Create a repository on database severs.
  hosts: database
  tasks:
    - name: Import GPG Public Key
      rpm_key:
        key:  http://repo.mysql.com/RPM-GPG-KEY-mysql
        state: present
    - name: Add repository on database servers
      yum_repository:
        name: mysql56-community
        file: external_repos
        description: "MySQL56 5.6 YUM Repo"
        baseurl: http://repo.mysql.com/yum/mysql5.6-community/el7/x86_64
        gpcheck: yes
        enabled: yes
        state: present

