---
- name: System facts configuration
  hosts: all
  vars:
    min_ram_mb: 1024
  tasks:
    - name: Sho System Requirments Message
      fail:
        msg: Server {{ inventory_hostname }} memeory less than 1024MB
      when: > 
        ansible_memtotal_mb < min_ram_mb

    - name: Set Swappiness value
      sysctl:
        name: vm.swappiness
        value: '5'
        state: present

