---
# tasks file for sample-mysql
- name: Tasks 9 
 # vars_files: secret.yml
  tasks:
    - name: Create partition
      parted:
        device: /dev/sdb
        number: 1
        state: present
        part_end: 800MB
    - name: LVM Volume Group
      lvg:
        vg: vg_database
        pvs: /dev/sdb1
        state: present
    - name: LVM Logical Volume     
      lvol:
        lv: lv_mysql
        vg: vg_database
        size: 512m
    - name: XFS filesystem
      filesystem:
        fstype: xfs
        dev: /dev/vg_database/lv_mysql
    - name: Mount LVM
      mount:
        path: /mnt/mysql_backups
        src: /dev/vg_database/lv_mysql
        fstype: xfs
        state: mounted

    - name: Install MySQL Community Server
      yum:
        name: mariadb-server
        state: present
    - name: Configure Firewall
      firewalld:
        port: 3306/tcp
        permanent: yes
        state: enabled
    - name: Set db password
      user:
        name: root
        password: "{{ database_password | password_hash('sha512', 'A512') }}" 
    - name: Start and Enable MySQL
      service:
        name: mariadb
        enabled: yes
        state: started
    - name: Deploy Template
      template:
        src: index.j2
        dest: /etc/my.cnf
        owner: root
        group: root
        mode: 0644
    - name: restart mariadb service
      service:
        name: mariadb
        state: restarted
  #    notify: restart mariadb service



        



